services:
  lsync:
    build: .
    volumes:
      - ./song:/app/song
      - ./output:/app/output
      - ./dataset:/app/dataset
      - huggingface_cache:/root/.cache/huggingface
      - torch_cache:/root/.cache/torch

volumes:
  huggingface_cache:
  torch_cache:
